name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v4
      
      - name: Setup NodeJs 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-js-
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
      - name: Commit and Push new README.md to the repository
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add README.md
          git commit -m "Auto-update README" || echo "No changes to commit"
          git push
